language: python
python:
  - "2.7"
  - "3.5"
env:
  matrix:
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
install:
  - pip install Django==$DJANGO_VERSION coveralls
  - python setup.py install
script: coverage run --source='.' --omit *runner* setup.py test
after_success:
  - coveralls
